export const ActionTypes = {
  ADD_TODO: "ADD_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  SET_TODO: "SET_TODO",
  EMPTY_TODO: "EMPTY_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
};
